image: golang:alpine

stages:
  - Create Test DB
  - Run Test

debug:
  stage: Create Test DB
  services:
    - postgres:15.3-alpine3.18
  variables:
    POSTGRES_DB: deslfy
    POSTGRES_USER: root
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust
    TZ: Europe/Istanbul
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add --no-cache make
  script:
    - echo "Database service started"
    - ping postgres -c 5
    - nslookup postgres
    - cat /etc/resolv.conf
    - curl http://ifconfig.me/ip
    - make migrateup
  tags:
    - deploy-runner
  when: manual

db_create:
  stage: Create Test DB
  services:
    - postgres:15.3-alpine3.18
  variables:
    POSTGRES_DB: deslfy
    POSTGRES_USER: root
    POSTGRES_PASSWORD: secret
    POSTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust
    TZ: Europe/Istanbul
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add --no-cache make
  script:
    - echo "Database service started"
    - curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.1/migrate.linux-amd64.tar.gz | tar xvz
    - mv migrate /usr/bin/migrate
    - which migrate
    - make migrateup
  tags:
    - deploy-runner
  when: manual

run_tests:
  stage: Run Test
  needs:
    - job: db_create
  variables:
    DNS_SERVER: 8.8.8.8
  before_script:
    - apk add --no-cache make
  script:
    - make test
  tags:
    - deploy-runner
  when: manual