image: golang:1.20.5-alpine3.18

stages:
  - Test
  - Build

db_create_test:
  stage: Test
  services:
    - postgres:15.3-alpine3.18
  variables:
    POSTGRES_DB: deslfy
    POSTGRES_USER: root
    POSTGRES_PASSWORD: secret
    POSTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust
    TZ: Europe/Istanbul
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add --no-cache make
  script:
    - echo "Database service started"
    - curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.1/migrate.linux-amd64.tar.gz | tar xvz
    - mv migrate /usr/bin/migrate
    - which migrate
    - make migrateup
    - make test
  tags:
    - deploy-runner
  when: manual

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_image:
  stage: Build
  image: 
    name: amazon/aws-cli:2.11.27
    entrypoint: [""]
  services:
    - docker:23.0.6-dind-alpine3.18
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - docker run docker:23.0.6 apk update
    - docker run docker:23.0.6 apk upgrade
    - docker run docker:23.0.6 apk add --no-cache curl jq
  script:
    - cd src/;
    - |
      echo $APP_ENV | jq -Rs 'split(" ") | map(split("=") | {(.[0]): .[1]}) | add' > env.json
      cat env.json | jq -r 'to_entries[] | "\(.key)=\(.value)"' > app.env
    - docker build -t $AWS_DOCKER_REGISTRY_URI/deslfy:latest -t $AWS_DOCKER_REGISTRY_URI/deslfy:${CI_COMMIT_SHORT_SHA} .
    - aws ecr get-login-password | docker login -u AWS $AWS_DOCKER_REGISTRY_URI --password-stdin
    - docker push $AWS_DOCKER_REGISTRY_URI/deslfy:${CI_COMMIT_SHORT_SHA}
  tags:
    - deploy-runner
  when: manual
