image: golang:alpine

stages:
  - Create Test DB
  - Run Test

db_create:
  stage: Create Test DB
  services:
    - postgres:15.3-alpine3.18
  variables:
    POSTGRES_DB: deslfy
    POSTGRES_USER: root
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - echo "Database service started"
    - curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.1/migrate.linux-amd64.tar.gz | tar xvz
    - mv migrate.linux-amd64 /usr/bin/migrate
    - which migrate
    - make migrateup
  tags:
    - deploy-runner
  when: manual

run_tests:
  stage: Run Test
  needs:
    - job: db_create
  script:
    - make test
  when: manual