services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    networks:
      - deslfy-network
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - src/app.env
  
  api:
    depends_on:
      - postgres
    image: deslfy:${CI_COMMIT_SHORT_SHA}
    restart: always
    networks:
      - deslfy-network
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - src/app.env
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

networks:
  deslfy-network:
    driver: bridge

volumes:
  db_data:
