// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Desly struct {
	ID        int32     `json:"id"`
	Redirect  string    `json:"redirect"`
	Desly     string    `json:"desly"`
	Clicked   int64     `json:"clicked"`
	CreatedAt time.Time `json:"created_at"`
	Owner     string    `json:"owner"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UserToken struct {
	ID        int32     `json:"id"`
	Owner     string    `json:"owner"`
	Token     string    `json:"token"`
	ExpireAt  time.Time `json:"expire_at"`
	CreatedAt time.Time `json:"created_at"`
}
