// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: rpc_create_desly.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDeslyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Redirect string `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
}

func (x *CreateDeslyRequest) Reset() {
	*x = CreateDeslyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_desly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeslyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeslyRequest) ProtoMessage() {}

func (x *CreateDeslyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_desly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeslyRequest.ProtoReflect.Descriptor instead.
func (*CreateDeslyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_desly_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeslyRequest) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

type CreateDeslyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desly *Desly `protobuf:"bytes,1,opt,name=desly,proto3" json:"desly,omitempty"`
}

func (x *CreateDeslyResponse) Reset() {
	*x = CreateDeslyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_desly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeslyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeslyResponse) ProtoMessage() {}

func (x *CreateDeslyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_desly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeslyResponse.ProtoReflect.Descriptor instead.
func (*CreateDeslyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_desly_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeslyResponse) GetDesly() *Desly {
	if x != nil {
		return x.Desly
	}
	return nil
}

var File_rpc_create_desly_proto protoreflect.FileDescriptor

var file_rpc_create_desly_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x73,
	0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x64, 0x65,
	0x73, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x22, 0x36, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x6c, 0x79, 0x52, 0x05, 0x64, 0x65,
	0x73, 0x6c, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x64, 0x65, 0x73, 0x6c, 0x66, 0x79, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_desly_proto_rawDescOnce sync.Once
	file_rpc_create_desly_proto_rawDescData = file_rpc_create_desly_proto_rawDesc
)

func file_rpc_create_desly_proto_rawDescGZIP() []byte {
	file_rpc_create_desly_proto_rawDescOnce.Do(func() {
		file_rpc_create_desly_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_desly_proto_rawDescData)
	})
	return file_rpc_create_desly_proto_rawDescData
}

var file_rpc_create_desly_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_desly_proto_goTypes = []interface{}{
	(*CreateDeslyRequest)(nil),  // 0: pb.CreateDeslyRequest
	(*CreateDeslyResponse)(nil), // 1: pb.CreateDeslyResponse
	(*Desly)(nil),               // 2: pb.Desly
}
var file_rpc_create_desly_proto_depIdxs = []int32{
	2, // 0: pb.CreateDeslyResponse.desly:type_name -> pb.Desly
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_desly_proto_init() }
func file_rpc_create_desly_proto_init() {
	if File_rpc_create_desly_proto != nil {
		return
	}
	file_desly_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_desly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeslyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_desly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeslyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_desly_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_desly_proto_goTypes,
		DependencyIndexes: file_rpc_create_desly_proto_depIdxs,
		MessageInfos:      file_rpc_create_desly_proto_msgTypes,
	}.Build()
	File_rpc_create_desly_proto = out.File
	file_rpc_create_desly_proto_rawDesc = nil
	file_rpc_create_desly_proto_goTypes = nil
	file_rpc_create_desly_proto_depIdxs = nil
}
