// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Desly struct {
	ID        int32     `json:"id"`
	Redirect  string    `json:"redirect"`
	Desly     string    `json:"desly"`
	Clicked   int64     `json:"clicked"`
	CreatedAt time.Time `json:"created_at"`
}
