// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateDesly(ctx context.Context, arg CreateDeslyParams) (Desly, error)
	GetDesly(ctx context.Context, id int32) (Desly, error)
	GetRedirectByDesly(ctx context.Context, desly string) (Desly, error)
}

var _ Querier = (*Queries)(nil)
