apiVersion: apps/v1
kind: Deployment
metadata:
  name: deslfy-redis-deployment
  labels:
    app: deslfy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deslfy-redis
      type: db
  template:
    metadata:
      labels:
        app: deslfy-redis
        type: db
    spec:
      containers:
      - name: deslfy-redis-db
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 512Mi
            cpu: "0.4"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deslfy-api-deployment
  labels:
    app: deslfy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deslfy-api
  template:
    metadata:
      labels:
        app: deslfy-api
    spec:
      containers:
      - name: deslfy-api
        image: 890813538613.dkr.ecr.eu-central-1.amazonaws.com/deslfy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 9090
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: REDIS_HOST
          value: deslfy-redis-deployment
        - name: REDIS_PORT
          value: "6379"