apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deslfy-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: "api.deslfy.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deslfy-api-service
            port:
              number: 80
  - host: "deslfy.com"
    http:
      paths:
      - pathType: Prefix
        path: "/r/"
        backend:
          service:
            name: deslfy-api-service
            port:
              number: 80
  tls:
  - hosts:
    - deslfy.com
    secretName: deslfy-api-cert
