apiVersion: v1
kind: Service
metadata:
  name: deslfy-api-service
spec:
  selector:
    app: deslfy-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 81
      targetPort: 8081
    - protocol: TCP
      port: 90
      targetPort: 9090
  type: ClusterIP