apiVersion: v1
kind: Service
metadata:
  name: deslfy-api-service
spec:
  selector:
    app: deslfy-api
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http-gateway-port
      protocol: TCP
      port: 81
      targetPort: 8081
    - name: grpc-port
      protocol: TCP
      port: 90
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service        
metadata:
  name: deslfy-redis-service
spec:
  selector:
    app: deslfy-redis
    type: db
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP